name: "Test PR Creation"

on:
  push:
    branches:
      - 'docs/version-*'


jobs:
  # setbranch:
  #   name: Get working branch
  #   runs-on: ubuntu-latest
  #   outputs:
  #     extract_branch: ${{ steps.extract_branch.outputs.branch }}
  #   steps:
  #     - name: Branch used
  #       id: extract_branch
  #       run: |
  #         if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
  #           echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
  #         elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
  #           echo "::set-output name=branch::$(echo $GITHUB_BASE_REF)"
  #         else
  #           echo "::set-output name=branch::INVALID_EVENT_BRANCH_UNKNOWN"
  #         fi
  
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Just Create A Pull Request
        # You may pin to the exact commit or the version.
        # uses: thomaseizinger/create-pull-request@955adb4634198898bc24dca0468514c63a8fc98d
        uses: thomaseizinger/create-pull-request@1.4.0
        with:
          # A GitHub API token
          github_token: ${{ secrets.PAT_KEY }}
          # The head ref that should be pulled into base.
          head: ${{ github.ref_name }}
          # The title of the pull request.
          title: "docs: add versioned docs for"
          # The base branch for the pull request. Defaults to master.
          base: "master"
          # The body of the pull request.
          body: "This PR adds the versioned docs for"
           
          